### ISSUE TITLE
sketchplugin?

### ISSUE THREAD

**Issue by MamaMightyMac** [sketch-hq/sketch-ipsum#1]
maybe its me. probably is, but I've downloaded this 3 times, no actual plugin to "doubleclick." When I doubleclick on the json files it opens dreamweaver...

**Comment by bomberstudios** [comment]
The link to download the plugin is on the README https://github.com/BohemianCoding/sketch-ipsum/releases/latest/download/sketch-ipsum.sketchplugin.zip
