### ISSUE TITLE
Not available in the plug in menue

### ISSUE THREAD

**Issue by mischugo** [sketch-hq/sketch-ipsum#3]
Have installed the plugin, but it is not available in the plug in menue (Sketch 56.3)

Cheers

**Comment by migueldelodo** [comment]
It's not working actually. Bad thing. ¿Any other option?

**Comment by bomberstudios** [comment]
The plugin is available in the Data menu:

- right click a text layer and choose 'Data', or
- use the Layer › Data menu option, or
- use the Data icon in the Toolbar
